### ISSUE TITLE
Bug: podman_containers not working

### ISSUE THREAD

**Issue by daniel-wtd** [containers/ansible-podman-collections#117]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using podman_containers, I am getting the below situation.

**Steps to reproduce the issue:**

1. Install the collection with `ansible-galaxy collection install containers.podman`
2. Create a playbook like below
3. Run the playbook via ansible-playbook

**Describe the results you received:**

In the first run, everything worked and the playbook was executed.
Every test after the initial one is showing issues.
The container is not started.

**Describe the results you expected:**

A container is started on the target machine and running busybox.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `ansible --version`:**

```
ansible 2.10.1
  config file = /var/home/dschier/Projects/laplab/ansible.cfg
  configured module search path = ['/var/home/dschier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/dschier/.venv-python3/lib64/python3.8/site-packages/ansible
  executable location = /var/home/dschier/.venv-python3/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

**Output of `podman version`:**

```
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: nb01
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.12-200.fc32.x86_64
  linkmode: dynamic
  memFree: 286470144
  memTotal: 16600121344
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8364486656
  swapTotal: 8371826688
  uptime: 84h 27m 17.54s (Approximately 3.50 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/dschier/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/dschier/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 18
  runRoot: /run/user/1000
  volumePath: /var/home/dschier/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 21:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
---
- hosts: localhost
  connection: local

  tasks:

    - name: Create container
      containers.podman.podman_container:
        name: mydata
        image: busybox
        command: sleep 3000
```

**Command line and output of ansible run with high verbosity:**

```
ansible-playbook 2.10.1
  config file = None
  configured module search path = ['/var/home/dschier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/dschier/.venv-python3/lib64/python3.8/site-packages/ansible
  executable location = /var/home/dschier/.venv-python3/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
No config file found; using defaults
Parsed localhost, inventory source with host_list plugin

PLAYBOOK: container-iot.yml *****************************************************************************
1 plays in container-iot.yml

PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
task path: /var/home/dschier/Projects/container-iot.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dschier
<localhost> EXEC /bin/sh -c 'echo ~dschier && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/home/dschier/.ansible/tmp `"&& mkdir "` echo /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167 `" && echo ansible-tmp-1601970919.5963953-210560-34787772624167="` echo /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /var/home/dschier/.venv-python3/lib64/python3.8/site-packages/ansible/modules/setup.py
<localhost> PUT /var/home/dschier/.ansible/tmp/ansible-local-2105504st2r_v5/tmp7pbm3d6c TO /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167/ /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/home/dschier/.ansible/tmp/ansible-tmp-1601970919.5963953-210560-34787772624167/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution fedora 32 on host localhost should use /usr/bin/python3, but is 
using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release 
will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more 
information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]
META: ran handlers

TASK [Create container] *********************************************************************************
task path: /var/home/dschier/Projects/container-iot.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dschier
<localhost> EXEC /bin/sh -c 'echo ~dschier && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/home/dschier/.ansible/tmp `"&& mkdir "` echo /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805 `" && echo ansible-tmp-1601970920.596172-210634-176221820881805="` echo /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805 `" ) && sleep 0'
Using module file /var/home/dschier/.ansible/collections/ansible_collections/containers/podman/plugins/modules/podman_container.py
<localhost> PUT /var/home/dschier/.ansible/tmp/ansible-local-2105504st2r_v5/tmppxgvmy3i TO /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/ /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py", line 102, in <module>
    _ansiballz_main()
  File "/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_container_payload_8bysk9p_/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 832, in <module>
ModuleNotFoundError: No module named 'yaml'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/home/dschier/.ansible/tmp/ansible-tmp-1601970920.596172-210634-176221820881805/AnsiballZ_podman_container.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_containers.podman.podman_container_payload_8bysk9p_/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 832, in <module>\nModuleNotFoundError: No module named 'yaml'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **********************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by HolgerHees** [comment]
you must install the yaml python module on your target machine

'''
ModuleNotFoundError: No module named 'yaml'
'''

**Comment by daniel-wtd** [comment]
Hi @HolgerHees, 

thanks a lot for the response. I have installed python3-pyyaml on the target system and tried again.

Unfortunately, this dependency wasn't documented here: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html, so I missed it.

**Comment by HolgerHees** [comment]
I added the dependency documentation as part of another bugfix

https://github.com/containers/ansible-podman-collections/pull/115/commits/7c64cd4f33a1a08a9b7e7d66f75632817369e5ec

**Comment by daniel-wtd** [comment]
@HolgerHees Thanks a ton. :+1:

**Comment by sshnaidm** [comment]
@daniel-wtd in next release it won't be required anymore. I removed last requirements of pyyaml.
