### ISSUE TITLE
"list index out of range" on pull task during check mode

### ISSUE THREAD

**Issue by Madic-** [containers/ansible-podman-collections#200]
/kind bug

**Description**

Pulling images in check mode leads to a "list index out of range".

**Steps to reproduce the issue:**

1. Create playbook.
```
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Container | Pull traefik/whoami:latest
      containers.podman.podman_image:
        name: traefik/whoami:latest
    - name: Container | whoami
      containers.podman.podman_container:
        image: "traefik/whoami:latest"
        restart_policy: always
        name: whoami
        state: started
        privileged: no
```

2. Run ansible-playbook whoami.yml --diff -C

Task crashes with "list index out of range".
```
TASK [Container | Pull traefik/whoami:latest] **********************************************************************************************************************************************************************
Thursday 18 February 2021  10:41:20 +0100 (0:00:01.298)       0:00:01.298 *****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [host.example]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_image_payload_nzo4r1if/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py", line 779, in <module>
  File "/tmp/ansible_containers.podman.podman_image_payload_nzo4r1if/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py", line 774, in main
  File "/tmp/ansible_containers.podman.podman_image_payload_nzo4r1if/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py", line 422, in __init__
  File "/tmp/ansible_containers.podman.podman_image_payload_nzo4r1if/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py", line 474, in present
IndexError: list index out of range
```

**Describe the results you expected:**

The task should check if a pull is required.

**Output of `ansible --version`:**

```
ansible 2.10.5
  config file = /home/mne-adm/Git/ansible-info/playbooks/ansible.cfg
  configured module search path = ['/home/mne-adm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/mne-adm/Git/ansible-info/roles/external/kubernetes-sigs.kubespray/library']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Feb  6 2021, 06:49:13) [GCC 10.2.0]
```

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Thu Sep 24 17:58:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: host.example
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.1.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 53826404352
  memTotal: 67254517760
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 26843541504
  swapTotal: 26843541504
  uptime: 996h 52m 8.55s (Approximately 41.50 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 17:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

See above

**Comment by sshnaidm** [comment]
@Madic- please check if #214 helped.

**Comment by Madic-** [comment]
It works. Thank you
