### ISSUE TITLE
Podman volume throws keyerror if recreate is false

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [containers/ansible-podman-collections#211]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running a volume task without explicitly setting recreate to true, will throw a "keyerror uid" on second run.
example task:
```yaml
 - containers.podman.podman_volume:
   name: my_volume
   ```

**Steps to reproduce the issue:**

1. run example task
2. run example task again

**Describe the results you received:**
 Throws error and exits on second run. (workaround: explicitly setting ```recreate: true```. However, breaks idempotency):
```sh


TASK [podman : configure | podman volume] **************************************
task path: /vagrant/roles/podman/tasks/configure/volume.yml:2
<node-1> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<node-1> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<node-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818 `" && echo ansible-tmp-1614182555.6810992-2358-66639049583818="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818 `" ) && sleep 0'
Using module file /vagrant/collections/ansible_collections/containers/podman/plugins/modules/podman_volume.py
<node-1> PUT /home/vagrant/.ansible/tmp/ansible-local-2229yos5fx5j/tmp35r0nbir TO /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py
<node-1> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/ /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py && sleep 0'
<node-1> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qwpqmqbzowxrtupraqgdfahuvyvufnhi ; /usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py'"'"' && sleep 0'
<node-1> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_volume', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 477, in <module>
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 473, in main
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 428, in execute
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 438, in make_present
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 307, in different
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 260, in is_different
  File "/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py", line 239, in diffparam_options
KeyError: 'uid'
failed: [node-1] (item={'name': 'nbtv_vol', 'state': 'present', 'options': [], 'recreate': False}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "name": "nbtv_vol",
        "options": [],
        "recreate": false,
        "state": "present"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1614182555.6810992-2358-66639049583818/AnsiballZ_podman_volume.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_volume', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 477, in <module>\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 473, in main\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 428, in execute\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 438, in make_present\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 307, in different\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 260, in is_different\n  File \"/tmp/ansible_containers.podman.podman_volume_payload_ilo_y_os/ansible_containers.podman.podman_volume_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_volume.py\", line 239, in diffparam_options\nKeyError: 'uid'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
node-1                     : ok=0   changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```

**Describe the results you expected:**
No changes to occur, no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens each subsequent run after first

**Output of `ansible --version`:**

```
2.10.6
```

**Output of `podman version`:**

```
3.0.1
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.26-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0e155c83aa739ef0a0540ec9f9d265f57f68038b'
  cpus: 1
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: node-1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 5.10.16-arch1-1
  linkmode: dynamic
  memFree: 1697636352
  memTotal: 2077368320
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc93-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.15.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.8-1
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 536866816
  swapTotal: 536866816
  uptime: 30m 45.77s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /home/vagrant/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.4.0-1
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/vagrant/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/vagrant/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613921386
  BuiltTime: Sun Feb 21 15:29:46 2021
  GitCommit: c640670e85c4aaaff92741691d6a854a90229d8d
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.0.1

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vagrant (archlinux/archlinux box)

**Comment by sshnaidm** [comment]
@k6Q28k5w5eWuRuuzTg9j7GrKCbjt7 can you please try the latest version? Either from galaxy or from repository. I suspect you use old version of ansible podman collection.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
@sshnaidm You're right, somehow it wasn't pulling in the latest. I can confirm this isn't an issue on version 1.4.3. My apologies for the mistake
