### ISSUE TITLE
"TypeError: NoneType is not iterable" when exposed port is not published

### ISSUE THREAD

**Issue by dsedivec** [containers/ansible-podman-collections#320]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Getting `TypeError: NoneType is not iterable` exception using `podman_container`.

**Steps to reproduce the issue:**

1. Use `podman_container` against up-to-date Fedora 34 with a running container having a `Dockerfile` that exposes ports which are not published

**Describe the results you received:**

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1633845463.802455-64007-119392584841699/AnsiballZ_podman_container.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1633845463.802455-64007-119392584841699/AnsiballZ_podman_container.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1633845463.802455-64007-119392584841699/AnsiballZ_podman_container.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=dict(_module_fqn='ansible_collections.containers.podman.plugins.modules.podman_container', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1006, in <module>
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1001, in main
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1669, in execute
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1605, in make_created
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1362, in different
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1289, in is_different
  File "/tmp/ansible_containers.podman.podman_container_payload_7ycoo113/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1117, in diffparam_publish
TypeError: 'NoneType' object is not iterable
```

**Describe the results you expected:**

No exceptions

**Additional information you deem important (e.g. issue happens only occasionally):**

Sorry I don't have a good reproduction case for this, but I think it's pretty straightforward to diagnose.  [Here's the line in question with the error](https://github.com/containers/ansible-podman-collections/blob/f56ea8322c2d074077137158720b5e6a5dced7fc/plugins/module_utils/podman/podman_container_lib.py#L1117).  Output of `podman container inspect $the_container` includes:

```
            "PortBindings": {
                "135/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "135"
                    }
                ],
                "137/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "137"
                    }
                ],
                "138/udp": null,
                "139/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "139"
                    }
                ],
                "445/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "445"
                    }
                ]
            },
```

I strongly suspect that `"138/udp": null` is the problem, since it's the iteration over `hosts` that's failing.  The `Dockerfile` in this case includes:

```
EXPOSE 137/udp 138/udp 139 445
```

The Ansible task for this leaves out 138/udp:

```
- name: Create container
  containers.podman.podman_container:
[...]
    publish:
      - '139:139/tcp'
      - '445:445/tcp'
      - '135:135/udp'
      - '137:137/udp'
  register: container
```

**Version of the `containers.podman` collection:** 
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
$ ansible-galaxy collection list | grep containers.podman
containers.podman 1.8.1
containers.podman             1.8.0
```

(Two versions is strange, I just updated them with `ansible-galaxy collection -U containers.podman`...  The line number in the exception checks out with the updated 1.8.1 version, in any case.)

**Output of `ansible --version`:**

```
$ ansible --version
ansible [core 2.11.5]
  config file = /Users/dale/repositories/repo/ansible.cfg
  configured module search path = ['/Users/dale/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dale/.vpy/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/dale/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/dale/.vpy/3.9/bin/ansible
  python version = 3.9.7 (default, Sep  1 2021, 12:35:15) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 2.11.3
  libyaml = True
```

**Output of `podman version`:**

```
# podman version
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 14:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: bobby
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.9-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 761167872
  memTotal: 16665423872
  ociRuntime:
    name: crun
    package: crun-1.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.1
      commit: 5b341a145c4f515f96f55e3e7760d1c79ec3cf1f
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 16884686848
  swapTotal: 17179860992
  uptime: 52h 18m 51.36s (Approximately 2.17 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 8
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 65
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 14:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-3.4.0-1.fc34.x86_64
```

**Playbook you run with ansible (e.g. content of `playbook.yaml`):**

Sorry, too big to include

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

Sorry, unavailable

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 34 x86-64, up-to-date as of 2021-10-10

**Comment by zephyros-dev** [comment]
I also met with the same error yesterday, but in my case it was the tag of the container that cause it. Here's how to reproduce:
1. Run a container with a number tagging, something like:
```
- name: HTTP Echo Container
  containers.podman.podman_container:
    name: "echo-test"
   # Notice the tag 20 here
    image: "mendhak/http-https-echo:20"
    ports:
      - "18080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro,z"
    restart_policy: on-failure
    state: "started"
```
2. It run normally the first time, but if you try to run it the 2nd time it would throw out the exact same error.
3. Setting the state to **absent** can still remove the running container
4. Rerun the above task, but change the tag to latest
5. It behaves normally

**Comment by sshnaidm** [comment]
I see, this is a regression with Podman 3.4.0. With lower versions it works fine. Will submit an issue there.
