### ISSUE TITLE
KeyError 'exitcommand'

### ISSUE THREAD

**Issue by AckslD** [containers/ansible-podman-collections#391]
/kind bug

**Description**

I'm getting an error whenever running a podman module. See below.

**Steps to reproduce the issue:**

For example when running the playbook:
```yaml
---
- name: SWAG server config
  hosts: all
  tasks:
    - name: Mariadb container
      containers.podman.podman_container:
        name: mariadb
        image: ghcr.io/linuxserver/mariadb
        state: started
        restart_policy: "unless-stopped"
        network: swag
        env:
          PUID: 1000
          PGID: 1000
          MYSQL_ROOT_PASSWORD: password
          TZ: Europe/London
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        volume:
          - /home/axel/swag/mariadb/config:/config
          - /home/axel/swag/mariadb/run:/run/mysqld
```

**Describe the results you received:**
When running a second time I get the error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/axel/.ansible/tmp/ansible-tmp-1647098513.636956-11556-218852096708052/AnsiballZ_podman_container.py", line 107, in <module>
    _ansiballz_main()
  File "/home/axel/.ansible/tmp/ansible-tmp-1647098513.636956-11556-218852096708052/AnsiballZ_podman_container.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/axel/.ansible/tmp/ansible-tmp-1647098513.636956-11556-218852096708052/AnsiballZ_podman_container.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=dict(_module_fqn='ansible_collections.containers.podman.plugins.modules.podman_container', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1025, in <module>
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1020, in main
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1643, in execute
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1556, in make_started
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1336, in different
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1263, in is_different
  File "/tmp/ansible_containers.podman.podman_container_payload_hn8ne3_l/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 965, in diffparam_log_level
KeyError: 'exitcommand'
```

**Describe the results you expected:**
No error.

**Additional information you deem important (e.g. issue happens only occasionally):**
The call worked once but then not again.

I'm pretty new to `ansible` so might be doing something wrong but I guess a crash like this shouldn't happen anyway.

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
1.9.1
```

**Output of `ansible --version`:**

```
ansible [core 2.12.3]
  config file = /home/axel/dev/server/ansible.cfg
  configured module search path = ['/home/axel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/axel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True   
```

**Output of `podman version`:**

```
podman version 4.0.1
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: t430
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.16.14-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 7811170304
  memTotal: 8141824000
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.4.3-1
    path: /usr/bin/crun
    version: |-
      crun version 1.4.3
      commit: 61c9600d1335127eba65632731e2d72bc3f0b9e8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 14m 23.76s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/axel/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/axel/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/axel/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.1
  Built: 1645701170
  BuiltTime: Thu Feb 24 12:12:50 2022
  GitCommit: c8b9a2e3ec3630e9172499e15205c11b823c8107
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# pacman -Qi podman
Name            : podman
Version         : 4.0.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : conmon  containers-common  crun  fuse-overlayfs  iptables  libdevmapper.so=1.02-64  libgpgme.so=11-64  libseccomp.so=2-64  slirp4netns
Optional Deps   : apparmor: for AppArmor support
                  btrfs-progs: support btrfs backend devices
                  catatonit: --init flag support
                  netavark: for a new container-network-stack implementation
                  podman-compose: for docker-compose compatibility
                  podman-docker: for Docker-compatible CLI
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79.65 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Thu 24 Feb 2022 12:12:50 PM CET
Install Date    : Sat 12 Mar 2022 02:43:58 PM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
# playbook.yaml
---
- name: SWAG server config
  hosts: all
  tasks:
    - name: Mariadb container
      containers.podman.podman_container:
        name: mariadb
        image: ghcr.io/linuxserver/mariadb
        state: started
        restart_policy: "unless-stopped"
        network: swag
        env:
          PUID: 1000
          PGID: 1000
          MYSQL_ROOT_PASSWORD: password
          TZ: Europe/London
          MYSQL_DATABASE: nextcloud
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        volume:
          - /home/axel/swag/mariadb/config:/config
          - /home/axel/swag/mariadb/run:/run/mysqld
```

```
# hosts
192.168.2.7
```

```
# ansible.cfg
[defaults]
inventory = hosts
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
ansible-playbook playbook.yaml --check --diff
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AckslD** [comment]
Seems to be `--diff` that causes this, if I remove it the error does not occur

**Comment by AckslD** [comment]
I also get similar errors for eg the network module where it crashes cause `'plugins'` is not in `self.info` of `PodmanNetworkDiff`.

**Comment by AckslD** [comment]
Sorry seems to be duplicate of #387

But I think the issue with `'plugins'` for network is a separate issue.

**Comment by AckslD** [comment]
Maybe I should have opened another issue for the second thing but anyway the changes in #392 fix it for me
