### ISSUE TITLE
podman_load IndexError: list index out of range 

### ISSUE THREAD

**Issue by leonidas-o** [containers/ansible-podman-collections#579]
/kind bug

**Description**

I'm iterating over a list and loading images from locally stored tar packages.
Ansible failed with the error shown below in `Describe the results you received`. Checking on the node, although ansible returned with an error, all images have been loaded, seems loading is working but something afterwards throws an error and makes this task fail.

**Steps to reproduce the issue:**

1. Setup a yaml list like shown below

2. use podman_load module with a loop to load multiple tar packages

3. see the task failing throwing an error

**Describe the results you received:**

Failed task with the following error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py", line 107, in <module>
    _ansiballz_main()
  File "/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_load', init_globals=dict(_module_fqn='ansible_collections.containers.podman.plugins.modules.podman_load', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py", line 191, in <module>
  File "/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py", line 178, in main
  File "/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py", line 157, in load
IndexError: list index out of range
failed: [localhost] (item={'file': 'kube-proxy_v1_27_0.tar', 'name': 'registry.k8s.io/kube-proxy', 'tag': 'v1.27.0'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "file": "kube-proxy_v1_27_0.tar",
        "name": "registry.k8s.io/kube-proxy",
        "tag": "v1.27.0"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/MYUSER/.ansible/tmp/ansible-tmp-1681479173.13602-31872-156200981204434/AnsiballZ_podman_load.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_load', init_globals=dict(_module_fqn='ansible_collections.containers.podman.plugins.modules.podman_load', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py\", line 191, in <module>\n  File \"/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py\", line 178, in main\n  File \"/tmp/ansible_containers.podman.podman_load_payload_pks73z67/ansible_containers.podman.podman_load_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_load.py\", line 157, in load\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Describe the results you expected:**
Expecting that the images are loaded (which seems to work already) and the podman_load task is not failing afterwards.

**Additional information you deem important (e.g. issue happens only occasionally):**

The list I'm iterating over:
```yaml
container_image_tag_list_k8s_1_27_0:
  - { file: kube-proxy_v1_27_0.tar, name: registry.k8s.io/kube-proxy, tag: v1.27.0 }
  - { file: kube-controller-manager_v1_27_0.tar, name: registry.k8s.io/kube-controller-manager, tag: v1.27.0 }
  - { file: kube-scheduler_v1_27_0.tar, name: registry.k8s.io/kube-scheduler, tag: v1.27.0 }
  - { file: kube-apiserver_v1_27_0.tar, name: registry.k8s.io/kube-apiserver, tag: v1.27.0 }
     ...
```

**Output of `ansible --version`:**

```
ansible [core 2.13.3]
  config file = /srv/ops/kubeinstall-ansible/ansible.cfg
  configured module search path = ['/home/MYUSER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/MYUSER/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

```
Installed Packages
Name         : ansible
Version      : 6.3.0
Release      : 2.el9
Architecture : noarch
Size         : 255 M
Source       : ansible-6.3.0-2.el9.src.rpm
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.9
Built:        Tue Feb 28 17:34:15 2023
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: fd49ef99363f06fe6b6ab119070cd95c6cc7c35a'
  cpuUtilization:
    idlePercent: 99.96
    systemPercent: 0.02
    userPercent: 0.02
  cpus: 2
  distribution:
    distribution: '"rocky"'
    version: "9.1"
  eventLogger: journald
  hostname: kube-ctl1.local
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-162.22.2.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 137883648
  memTotal: 801443840
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 263h 49m 25.00s (Approximately 10.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/MYUSER/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/MYUSER/.local/share/containers/storage
  graphRootAllocated: 6641680384
  graphRootUsed: 2735665152
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  volumePath: /home/MYUSER/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1677602055
  BuiltTime: Tue Feb 28 17:34:15 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.2.0-11.el9_1.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
    - name: Podman load image
      containers.podman.podman_load:
        input: '{{ packages_path.container_images.k8s }}/{{ item.file }}'
      loop: '{{ k8s_container_image_tag_list }}'
      when: ctrl_node_container_tool == 'podman'
```
> `k8s_container_image_tag_list` == `container_image_tag_list_k8s_1_27_0 ` (list in `Additional information you deem important` section)

**Command line and output of ansible run with high verbosity**
Error message in section `Describe the results you received:`

**Comment by sshnaidm** [comment]
Which version of the collection is used? Can you please try to install the latest from Galaxy and try with it?
