### ISSUE TITLE
1.10.3 breaks python 2.7 compatibility

### ISSUE THREAD

**Issue by clementmartin** [containers/ansible-podman-collections#642]
/kind bug

**Description**

Using `podman_image` module with 1.10.3 fails with a syntax error if the target node is using python 2.7.

**Steps to reproduce the issue:**

1. Target a centos 7 machine

2. Use the `podman_image` module

3. See if fail with the following error:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py", line 259, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py", line 249, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py", line 123, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_containers.podman.podman_image_payload_1SubHA/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py", line 408, in <mod
ule>
  File "/tmp/ansible_containers.podman.podman_image_payload_1SubHA/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/common.py", line 165
    result['diff']['before'].update({f'systemd_{file_name}.service': ''})
                                                                  ^
SyntaxError: invalid syntax
fatal: [ip-10-100-11-105.devops.cias.one]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.100.11.105 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py\", line 259, in <module>\r\n
 _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py\", line 249, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp
_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1693989555.9963777-3653960-14345206715971/AnsiballZ_podman_image.py\", line 123, in invoke_module\r\n    run_name='__main__', alter
_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_
fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_containers.podman.podman_image_payload_1SubHA/ansible_
containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_image.py\", line 408, in <module>\r\n  File \"/tmp/ansible_containers.podman.podman_image_payload_1SubH
A/ansible_containers.podman.podman_image_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/common.py\", line 165\r\n    result['diff']['before'].update({f'systemd_{file_name}.serv
ice': ''})\r\n                                                                  ^\r\nSyntaxError: invalid syntax\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Issue was introduced in 7a307453a599f964e1f686e58ab49a56c4611013

Lines 168 and 169 of plugins/module_utils/podman/common.py are using "f-strings" which are python3 only.

**Comment by sshnaidm** [comment]
Same as #628 
And same question - why don't you install Python 3.6 which is provided for CentOS 7?
