### ISSUE TITLE
Podman Container fails with TypeError when rerunning the Playbook on Podman 2.0.1

### ISSUE THREAD

**Issue by jaudriga** [containers/ansible-podman-collections#65]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The Podman Container Module fails with `TypeError: string indices must be integers` when rerunning my playbooks on a host with podman 2.0.1 installed.

**Steps to reproduce the issue:**

1. Make sure you are using one of the latest podman 2.0.x release.

2. Start graphite container with below playbook code snippet:

3. Run the code snippet again

**Describe the results you received:**
Ansible failed with:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers
fatal: [graphite.exp]: FAILED! => {"changed": false, "module_stderr": "Shared connection to XXX.XXX.XXX.XXX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416552.0115376-5594-153592447270755/AnsiballZ_podman_container.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416552.0115376-5594-153592447270755/AnsiballZ_podman_container.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416552.0115376-5594-153592447270755/AnsiballZ_podman_container.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2070, in <module>\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2066, in main\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2046, in execute\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1983, in make_started\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1828, in different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1755, in is_different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1625, in diffparam_publish\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_t0vfb91k/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1626, in <listcomp>\r\nTypeError: string indices must be integers\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Describe the results you expected:**
Ansible ran through when using version < 2.0.1

**Additional information you deem important (e.g. issue happens only occasionally):**
2.0.0 broke idempotency once again (might be related or different issue), like in #61 . Now 2.0.1 completely broke the collection when rerunning the playbook.

**Output of `ansible --version`:**

```
ansible 2.9.10
  config file = /home/jrsr/repos/audriga-infra/ansible.cfg
  configured module search path = ['/home/jrsr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

**Output of `podman version`:**

```
Version:      2.0.1
API Version:  1
Go Version:   go1.13.8
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.18, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: graphite
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-1017-aws
  linkmode: dynamic
  memFree: 159105024
  memTotal: 2044592128
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.0
      commit: unknown
      libslirp: 4.2.0
  swapFree: 0
  swapTotal: 0
  uptime: 96h 40m 11.24s (Approximately 4.00 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/ubuntu/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/ubuntu/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/ubuntu/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.13.8
  OsArch: linux/amd64
  Version: 2.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.0.1~1 amd64 [installed]
podman/unknown 2.0.1~1 arm64
podman/unknown 2.0.1~1 armhf
podman/unknown 2.0.1~1 s390x
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
- name: Install Graphite container
  containers.podman.podman_container:
    image: "graphiteapp/graphite-statsd:1.1.7-3"
    name: graphite
    ports:
      - "80:80"
      - "443:443"
      - "2003-2004:2003-2004"
    state: present
    volumes:
      - "graphite-config:/opt/graphite/conf"
      - "graphite-data:/opt/graphite/storage"
      - "nginx-config:/etc/nginx"
      - "/etc/letsencrypt:/etc/letsencrypt"
```

**Command line and output of ansible run with high verbosity:**

```
ansible-playbook site.yml -CD --start-at-task 'Install Graphite container' -vvv
TASK [graphite : Install Graphite container] *************************************************************************************************************************************************
...
Escalation succeeded
<graphite.exp> (1, b'Traceback (most recent call last):\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.containers.podman.plugins.modules.podman_container\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib/python3.8/runpy.py", line 206, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2070, in <module>\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2066, in main\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2046, in execute\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1983, in make_started\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1828, in different\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1755, in is_different\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1625, in diffparam_publish\r\n  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1626, in <listcomp>\r\nTypeError: string indices must be integers\r\n', b'Shared connection to 34.251.65.188 closed.\r\n')
<graphite.exp> Failed to connect to the host via ssh: Shared connection to XXX.XXX.XXX.XXX closed.
<graphite.exp> ESTABLISH SSH CONNECTION FOR USER: None
<graphite.exp> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/jrsr/.ansible/cp/8193496df9 graphite.exp '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/ > /dev/null 2>&1 && sleep 0'"'"''
<graphite.exp> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2070, in <module>
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2066, in main
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 2046, in execute
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1983, in make_started
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1828, in different
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1755, in is_different
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1625, in diffparam_publish
  File "/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1626, in <listcomp>
TypeError: string indices must be integers
fatal: [graphite.exp]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to XXX.XXX.XXX.XXX closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1593416248.8279798-5071-6472735981908/AnsiballZ_podman_container.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2070, in <module>\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2066, in main\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 2046, in execute\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1983, in make_started\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1828, in different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1755, in is_different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1625, in diffparam_publish\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_2vkjv7be/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1626, in <listcomp>\r\nTypeError: string indices must be integers\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by sshnaidm** [comment]
Great, new podman, new issues :smile: 
Inspect format was changed :jack_o_lantern: Gonna fix.
From good news, now it's closer to `docker` one.

**Comment by jaudriga** [comment]
@sshnaidm Thanks for fixing this so fast :) .
