### ISSUE TITLE
Can't update container with command set to null

### ISSUE THREAD

**Issue by chris-crunchr** [containers/ansible-podman-collections#838]
/kind bug

**Description**

When I update `command` using `podman_container` on a container that did not have a command before, I get a traceback, complaining `NoneType` is not iterable.

**Steps to reproduce the issue:**

1. Create the following playbook:
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Setup scenario
    containers.podman.podman_container:
      name: test
      init: true
      image: docker.io/busybox
      entrypoint: "/bin/httpd -f"

  - name: Trigger bug
    containers.podman.podman_container:
      name: test
      init: true
      image: docker.io/busybox
      command: "/bin/httpd -f"
```
2. Run the playbook on some machine with podman installed (e.g. localhost).
3. The first task succeeds, but the second fails!

**Describe the results you received:**

```
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1377, in <module>
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1372, in main
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1918, in execute
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1801, in make_started
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1580, in different
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1501, in is_different
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1042, in diffparam_command
      File "/tmp/ansible_containers.podman.podman_container_payload__n2jwizy/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1020, in _join_quotes
    TypeError: 'NoneType' object is not iterable
```

**Describe the results you expected:**

I expected the container to be recreated with the right command.

**Version of the `containers.podman` collection:** 1.5.4

**Output of `ansible --version`:**

```
ansible [core 2.17.3]
  config file = /workspaces/INF-3017-upgrade-to-ubuntu-24.04-lts-on-/ansible.cfg
  configured module search path = ['/home/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/chris/.cache/pypoetry/virtualenvs/clustr-q1uNEsDK-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /workspaces/INF-3017-upgrade-to-ubuntu-24.04-lts-on-/shared/ansible/ansible_collections
  executable location = /home/chris/.cache/pypoetry/virtualenvs/clustr-q1uNEsDK-py3.10/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/home/chris/.cache/pypoetry/virtualenvs/clustr-q1uNEsDK-py3.10/bin/python)
  jinja version = 3.1.2
  libyaml = True```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.22.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.33.7
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.10+ds1-1build2_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: unknown'
  cpuUtilization:
    idlePercent: 93.74
    systemPercent: 2.49
    userPercent: 3.77
  cpus: 4
  databaseBackend: sqlite
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: journald
  freeLocks: 2043
  hostname: test
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.8.0-1013-azure
  linkmode: dynamic
  logDriver: journald
  memFree: 15445815296
  memTotal: 16766783488
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-5_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-4_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.4.0
  ociRuntime:
    name: runc
    package: containerd.io_1.7.21-1_amd64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.13
      commit: v1.1.13-0-g58aa920
      spec: 1.0.2-dev
      go: go1.22.6
      libseccomp: 2.5.5
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20240220.1e6f92b-1_amd64
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.1-1build2_amd64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 0h 20m 51.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 40483942400
  graphRootUsed: 6630305792
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/noble-updates,noble-security,now 4.9.3+ds1-1ubuntu0.1 amd64 [installed]
```

**Playbook you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Setup scenario
    containers.podman.podman_container:
      name: test
      init: true
      image: docker.io/busybox
      entrypoint: "/bin/httpd -f"

  - name: Trigger bug
    containers.podman.podman_container:
      name: test
      init: true
      image: docker.io/busybox
      command: "/bin/httpd -f"
```

**Command line and output of ansible run with high verbosity**

```
PLAY [test] *********************************************************

TASK [Setup scenario] **********************************************************
changed: [test]

TASK [Trigger bug] *************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [test]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1377, in <module>
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py", line 1372, in main
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1918, in execute
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1822, in make_started
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1580, in different
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1501, in is_different
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1042, in diffparam_command
      File "/tmp/ansible_containers.podman.podman_container_payload_4uo0wroc/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py", line 1020, in _join_quotes
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *********************************************************************
test            : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure VM.

**Comment by chris-crunchr** [comment]
Found a quick fix, that works for me. Not sure if it's the desired fix, so sharing it here as a comment:

```diff
diff --git a/plugins/module_utils/podman/podman_container_lib.py b/plugins/module_utils/podman/podman_container_lib.py
index 78af30f..c77d83a 100644
--- a/plugins/module_utils/podman/podman_container_lib.py
+++ b/plugins/module_utils/podman/podman_container_lib.py
@@ -1037,7 +1037,7 @@ class PodmanContainerDiff:
 
         # TODO(sshnaidm): to inspect image to get the default command
         if self.module_params['command'] is not None:
-            before = self.info['config']['cmd']
+            before = self.info['config']['cmd'] or ''
             after = self.params['command']
             before = _join_quotes(before)
             if isinstance(after, list):

**Comment by chris-crunchr** [comment]
Hit the wrong button. :sweat:

**Comment by sshnaidm** [comment]
@chris-crunchr please see if #839 solves it

**Comment by chris-crunchr** [comment]
Tested that change and it works for me! Thanks for the quick fix. :+1:
